defaults:
  - client: FEMNIST
  - fed: default
  - data: FEMNIST
  - state: default
  - strategy: fed_avg

wandb:
  setup:
    project: B_HFL_ICLR
    group: ${data.dataset_path}
    tags:
      - "strategy_${strategy.name}"
      - "net_${client.network}"
      - "seed_${fed.seed}"
    entity:
    mode: online