defaults:
  - _self_
  - client: FEMNIST
  - fed: default
  - data: FEMNIST
  - state: default
  - strategy: fed_avg

reuse_output_dir: Null

train_optimal: True
recursively_train_all_optimal_models: True

train_fed: True
recursively_fed_simulate_all: True


wandb:
  setup:
    project: B_HFL_ICLR
    group: ${data.dataset_path}
    tags:
      - "strategy_${strategy.name}"
      - "net_${client.network}"
      - "seed_${fed.seed}"
    entity:
    mode: online