---
defaults:
  - _self_
  - fed: default
  - data: default
  - state: default
  - strategy: fed_avg
  - plotting: default
  - task: femnist

reuse_output_dir: null
train_optimal: false
recursively_train_all_optimal_models: false
optimal_name: _optimal
optimal_type: ${optimal_name}_root_${task.data.client_folder}
train_fed: true
recursively_fed_simulate_all: false
fed_name: _fed
fed_type: ${fed_name}_root_${task.data.client_folder}
use_wandb: true
eval_only: false

wandb:
  mode: enabled
  setup:
    project: B_HFL_ICLR
    group: ${task.data.preparation.dataset_path}
    tags:
      - strategy_${strategy.name}
      - net_${task.client.network}
      - seed_${fed.seed}
    entity: null
    mode: online
