

# for "get_eviction_dataset_manager"
dataset_limit: 20
dataset_eviction_proportion: 0.5

# for "get_eviction_parameter_manager"
parameters_limit: 20
parameters_eviction_proportion: 0.5

get_recursive_builder:
  _target_: "client.get_recursive_builder_wrapper"
  
get_dataset_manager: 
  _target_: "state_management.get_eviction_dataset_manager"
  dataset_limit: ${state.dataset_limit}
  eviction_proportion: ${state.dataset_eviction_proportion}
  
get_load_parameters_file:
  _target_: "utils.load_parameters_file"

get_save_parameters_to_file:
  _target_: "utils.save_parameters_to_file"

get_parameter_manager:
  _target_: "state_management.get_eviction_parameter_manager"
  parameters_limit: ${state.parameters_limit}
  eviction_proportion: ${state.parameters_eviction_proportion}
