---
num_rounds: 10
num_clients_per_round: 1
num_total_clients: 1
num_evaluate_clients_per_round: 0
seed: 42
max_workers: null
gpus_per_client: 0
cpus_per_client: 1
timeout: null

get_on_fit_config_fn:
  _target_: b_hfl.utils.utils.get_config
  config_name: on_fit
  seed: ${fed.seed}

get_on_evaluate_config_fn:
  _target_: b_hfl.utils.utils.get_config
  config_name: on_evaluate
  seed: ${fed.seed}

get_initial_parameters:
  _target_: b_hfl.utils.utils.get_initial_parameters

get_on_fit_metrics_agg_fn:
  _target_: b_hfl.utils.utils.get_metrics_agg_fn

get_on_evaluate_metrics_agg_fn:
  _target_: b_hfl.utils.utils.get_metrics_agg_fn

plot_results:
  _target_: b_hfl.utils.utils.plot_metric_from_history
