alpha: 0.5


get_anc_node_opt:
  _target_: "node_optimizers.get_fedavg_weighted_node_opt"
  alpha: ${client.alpha}

get_desc_node_opt:
_target_: "node_optimizers.get_fedavg_weighted_node_opt"
alpha: ${client.alpha}
