---
network: CNN

# Default model training parameters
batch_size: 16
num_workers: 4
shuffle: false
client_learning_rate: 0.01
weight_decay: 0.001

# Default model testing parameters
test_batch_size: 32
test_num_workers: 4

get_net_generator:
  _target_: b_hfl.task.femnist.models.get_generate_model
  network: ${task.client.network}

get_anc_node_opt:
  _target_: b_hfl.node_optimizer.weighted_fed_avg.get_fedavg_weighted_node_opt

get_desc_node_opt:
  _target_: b_hfl.node_optimizer.weighted_fed_avg.get_fedavg_weighted_node_opt

get_test:
  _target_: b_hfl.task.femnist.train.test_femnist

get_optimizer_generator:
  _target_: b_hfl.task.femnist.train.optimizer_generator_femnist

get_train:
  _target_: b_hfl.task.femnist.train.train_femnist

# General client per-level cofniguration
client_train:
  num_rounds: [1, 1, 1, 1]
  train_children: [true, true, true, false]
  fit_fraction: [1, 1, 1, 0.0]
  train_chain: [false, false, false, true]
  epochs: [1, 1, 1, 5]
  train_proxy: [false, false, false, false]
  track_parameter_changes: [True, True, True, false]

# Node optimizer per-level configuration
node_opt:
  anc_alpha: [0.0, 0.0, 0.0, 0.0]
  desc_alpha: [0.0, 0.0, 0.0, 0.0]

### These are numbered in direction of data propagation
residuals:
  # This means that the root connects to the edge servers above the leaves
  root_to_leaf_residuals:
    - [-2]
    - []
    - []
    - []

  # This means that the edge servers connect to the root alone
  leaf_to_root_residuals:
    - []
    - []
    - [0]
    - []

client_test:
  test_children: [false, false, false, false]
  eval_fraction: [1.0, 1.0, 0.1, 0.0]
  test_chain: [true, true, true, true]
  test_proxy: [false, false, false, false]

get_config_mapping:
  _target_: b_hfl.task.femnist.config_generation.get_generate_level_configs
